In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [32]:
vec = (2 ** np.arange(start = 1, stop = 21)) / np.arange(start = 1, stop = 21)
np.around(vec, decimals = 3, out = vec)[18]

27594.105

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [52]:
v1 = np.arange(start = 0, stop = 16, step = 3)
v2 = np.arange(start = 0, stop = 21, step = 4)
np.dot(0.1 ** v1, 0.2 ** v2)

[ 0  3  6  9 12 15] [ 0  4  8 12 16 20]


1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [92]:
a = np.zeros((8,8))
a[0::1, 0::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [110]:
arr = np.random.random((5, 2))
x = arr[:, 0]
y = arr[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
fi = np.arctan(y/x)
X = np.array([r, fi]).T
X

array([[1.12296534, 0.59241978],
       [1.02237179, 1.25449513],
       [0.30084725, 0.04276519],
       [0.61184003, 1.50380431],
       [0.75186235, 1.30594585]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [119]:
X = np.random.random((10, 10))
print(np.unravel_index(np.argmax(X, axis = None), X.shape))

(4, 2)


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [134]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
X_x = X[:, 0]
X_y = X[:, 1]
y_x = y[:, 0]
y_y = y[:, 1]
ans = np.sqrt((X_x - y_x) ** 2 + (X_y - y_y) ** 2)
X[np.argmin(ans, axis = 0)]
## your code

array([0.33283074, 0.21090116])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [47]:
def func(x):
    int_1 = (x < 0)
    int_2 = ((x<2) * (x >= 0))
    int_3 = (x >= 2)
    x[int_1] = (x[int_1] ** 2 + 2 * x[int_1] + 6)
    x[int_3] = (x[int_3] ** 2 + 4 * x[int_3] - 4)
    x[int_2] = (x[int_2] + 6)
    return x
x = np.linspace(-3, 3, 100)
func(x)

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [158]:
X = np.random.random((10, 10))
a = [[1,1],[2,2]]

np.mean((X.T - np.mean(X, axis = 1)).T, axis = 1)
## your code

array([-1.11022302e-16, -3.33066907e-17,  2.22044605e-17, -2.22044605e-17,
        0.00000000e+00,  2.22044605e-17, -6.66133815e-17, -7.77156117e-17,
        0.00000000e+00,  1.11022302e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [138]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(X.mean(), X.std())

5.065082701638292 2.071560028368259


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [132]:
(np.arange(0, 5*6, 1) % 5).reshape(5, 6)[:, :5]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [10]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        print(val)
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 4)


41.48901553867807
21.433938001860305
6.492696090076132
74.83495800928252


[0, 0, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [64]:
arr, n = [50, 3, 1, 7, 20], 4
@np.vectorize
def sample(x):
    return np.sum(arr < x)
s = np.sum(arr)
arr = np.cumsum(arr)
x = s * np.random.random(n)
print(arr, x)

sample(x)

[50 53 54 61 81] [54.71676935 80.99361498 38.08989611 77.50512069]


array([3, 4, 0, 4])